# Generated by Django 5.1.3 on 2024-12-11 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Color",
                    models.CharField(
                        choices=[
                            ("Red", "Red"),
                            ("Blue", "Blue"),
                            ("Black", "Black"),
                            ("White", "White"),
                            ("Yellow", "Yellow"),
                            ("Green", "Green"),
                        ],
                        max_length=20,
                    ),
                ),
                ("InputPrice", models.FloatField()),
                ("OutputPrice", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=20)),
                ("Sex", models.CharField(max_length=20)),
                ("Age", models.IntegerField()),
                ("Phone", models.CharField(max_length=20)),
                ("Native_Addr", models.CharField(max_length=20)),
                ("Salary", models.FloatField()),
                ("Position", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Car_Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Num", models.IntegerField()),
                (
                    "Car_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="Stock.car"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Addr", models.CharField(max_length=20)),
                ("Capacity", models.IntegerField()),
                (
                    "CarStock",
                    models.ManyToManyField(through="Stock.Car_Stock", to="Stock.car"),
                ),
                (
                    "Staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="Stock.staff"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="car_stock",
            name="Stock_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Stock.stock"
            ),
        ),
    ]
