# Generated by Django 5.1.4 on 2024-12-15 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Basic", "0003_alter_car_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car_Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Num", models.IntegerField()),
                (
                    "Car_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="Basic.car"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Addr", models.CharField(max_length=20)),
                ("Capacity", models.IntegerField()),
                (
                    "CarStock",
                    models.ManyToManyField(through="Stock.Car_Stock", to="Basic.car"),
                ),
                (
                    "Staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="Basic.staff"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="car_stock",
            name="Stock_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Stock.stock"
            ),
        ),
    ]
