# Generated by Django 5.1.3 on 2024-12-12 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BasicInformaiton", "0001_initial"),
        ("InputStock", "0002_alter_car_supplier_car_id_alter_supplier_car_id"),
        ("OutputStock", "0002_alter_client_car_id_alter_order_car_id_and_more"),
        ("Stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car_stock",
            name="Car_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="BasicInformaiton.car",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="Staff_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="BasicInformaiton.staff",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="CarStock",
            field=models.ManyToManyField(
                through="Stock.Car_Stock", to="BasicInformaiton.car"
            ),
        ),
        migrations.DeleteModel(
            name="Car",
        ),
        migrations.DeleteModel(
            name="Staff",
        ),
    ]
