# Generated by Django 5.1.3 on 2024-12-12 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BasicInformaiton", "0001_initial"),
        ("InputStock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car_supplier",
            name="Car_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="BasicInformaiton.car",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="Car_id",
            field=models.ManyToManyField(
                through="InputStock.Car_Supplier", to="BasicInformaiton.car"
            ),
        ),
    ]
