# Generated by Django 5.1.3 on 2024-12-11 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=20)),
                ("Phone", models.CharField(max_length=20)),
                ("Addr", models.CharField(max_length=20)),
                (
                    "Work_Status",
                    models.IntegerField(choices=[(0, "unfinished"), (1, "finished")]),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField()),
                ("Total_Price", models.FloatField()),
                (
                    "Car_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="Stock.car"
                    ),
                ),
                (
                    "Client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="OutputStock.client",
                    ),
                ),
                (
                    "Staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="Stock.staff"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="client",
            name="Car_id",
            field=models.ManyToManyField(through="OutputStock.Order", to="Stock.car"),
        ),
    ]
