# Generated by Django 5.1.4 on 2024-12-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Basic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="name",
            field=models.CharField(default="Car", max_length=20),
        ),
    ]
