# Generated by Django 5.1.4 on 2024-12-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Basic", "0002_car_description_car_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
