# Generated by Django 5.1.4 on 2024-12-18 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Basic", "0004_staff_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="Name",
        ),
    ]
